// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using amir_apparel_demo_api_dotnet_5.Data.Context;

namespace amir_apparel_demo_api_dotnet_5.Migrations
{
    [DbContext(typeof(AppCtx))]
    [Migration("20211103004542_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("amir_apparel_demo_api_dotnet_5.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 10,
                            Description = "Description",
                            Material = "Random Material",
                            Name = "Random Name",
                            Price = 12.11m,
                            Status = true,
                            Type = "Random Type"
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 10,
                            Description = "Description",
                            Material = "Random Material",
                            Name = "Random Name",
                            Price = 12.11m,
                            Status = true,
                            Type = "Random Type"
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 10,
                            Description = "Description",
                            Material = "Random Material",
                            Name = "Random Name",
                            Price = 12.11m,
                            Status = true,
                            Type = "Random Type"
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 10,
                            Description = "Description",
                            Material = "Random Material",
                            Name = "Random Name",
                            Price = 12.11m,
                            Status = true,
                            Type = "Random Type"
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 10,
                            Description = "Description",
                            Material = "Random Material",
                            Name = "Random Name",
                            Price = 12.11m,
                            Status = true,
                            Type = "Random Type"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
